server:
  port: 8282

remote:
  maxTotalConnect: 1
  maxConnectPerRoute: 200
  connectTimeout: 2000
  readTimeout: 6000
spring:
  retry:
    backOffPolicy: 4000
    maxAttempts: 2
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  redis:
    timeout: 60000

service:
  location:
    url: http://3.249.37.231:8080/api/v1
    list:
      url: https://utils.blthouse.tech/location-ws/api/v1/countries
  notification:
    email:
      url: https://utils.blthouse.tech/notif-eu-ws/api/v1/support
      contact: support@icash-congo.com

  authentication:
    lastBefore :
      url : http://54.246.222.6:7070/api/v1/users
    base:
      url: https://utils.blthouse.tech/auth-ws/api/v1/users
    reset:
      url: https://utils.blthouse.tech/auth-ws/api/v1/users/reset-password
      #link: http://54.246.222.6:8080/reset-password
    update:
      url: https://utils.blthouse.tech/auth-ws/api/v1/users
      password:
        url: https://utils.blthouse.tech/auth-ws/api/v1/users/update-password
    create:
      url: https://utils.blthouse.tech/auth-ws/api/v1/users
    authenticate:
      url: https://utils.blthouse.tech/auth-ws/api/v1/users/authenticate
    info:
      url: https://utils.blthouse.tech/auth-ws/api/v1/users/info?token=%s

  opcc:
    admin:
      url: http://localhost:8081/api/v1/admin

#storage service
aws:
  bucket:
    name: opcc-resources
    location:
      public : static
  access:
    key: AKIA37Q5P7OWKY4JQ6Z7
  secret:
    key: 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

storage:
  service:
    default:
      location: C:/Users/USER/Documents/resources_bip
